"""baseline: esquema completo con las 12 funcionalidades nuevas

Revision ID: ca45c4c8ae3e
Revises: 
Create Date: 2026-09-08 16:40:50.218432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca45c4c8ae3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_conceptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('persona_fisica', 'empresa', name='tipo_cliente'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.Enum('materiales', 'equipo', 'servicios', 'otro', name='categoria_proveedor'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('oficio', sa.Enum('albanil', 'pintor', 'electricista', 'plomero', 'carpintero', 'ayudante_general', 'otro', name='oficio_trabajador'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_pago', sa.Enum('por_dia', 'destajo', 'semana', name='tipo_pago_trabajador'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'supervisor', 'empleado', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('levantamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo_obra', sa.Enum('residencial', 'comercial', 'publica', 'mixta', 'otro', name='tipo_obra'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('indicaciones_cliente', sa.Text(), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('nuevo', 'en_cotizacion', 'cotizado', 'descartado', name='estado_levantamiento'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('levantamiento_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'enviada', 'aceptada', 'rechazada', name='estado_cotizacion'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('respondida_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['levantamiento_id'], ['levantamientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('residencial', 'comercial', 'publica', 'mixta', 'otro', name='tipo_obra_ejec'), nullable=False),
    sa.Column('monto_contrato', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'pausada', 'terminada', 'cancelada', name='estado_obra'), nullable=False),
    sa.Column('avance_porcentaje', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_alerta_presupuesto', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cotizacion_id')
    )
    op.create_table('avance_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('etapa', sa.String(length=100), nullable=False),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('reportado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['reportado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('clima', sa.Enum('soleado', 'nublado', 'lluvioso', 'frio', 'caluroso', name='clima_bitacora'), nullable=False),
    sa.Column('personal_en_obra', sa.Integer(), nullable=True),
    sa.Column('actividades', sa.Text(), nullable=False),
    sa.Column('incidencias', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obra_id', 'fecha', name='uq_bitacora_obra_fecha')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('plano', 'licencia', 'contrato', 'acta', 'factura', 'otro', name='categoria_documento'), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('visible_cliente', sa.Boolean(), nullable=False),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('materiales', 'equipo', 'subcontratista', 'administrativo', 'otro', name='categoria_gasto'), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('fecha_recibido', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'recibido', 'vencido', 'cancelado', name='estado_pago_cliente'), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_mano_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('dias_o_unidades', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'terminada', name='estado_tarea'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_tarea'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bitacora_id', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=300), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bitacora_id'], ['bitacora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_fotos')
    op.drop_table('tareas')
    op.drop_table('pagos_mano_obra')
    op.drop_table('pagos_cliente')
    op.drop_table('gastos')
    op.drop_table('documentos')
    op.drop_table('bitacora')
    op.drop_table('avance_obra')
    op.drop_table('obras')
    op.drop_table('cotizacion_items')
    op.drop_table('cotizaciones')
    op.drop_table('levantamientos')
    op.drop_table('clientes_acceso')
    op.drop_table('usuarios')
    op.drop_table('trabajadores')
    op.drop_table('proveedores')
    op.drop_table('clientes')
    op.drop_table('catalogo_conceptos')
    # ### end Alembic commands ###
